### ISSUE TITLE
Runway 12 and 23 for arr, Rwy 23 for dep at YPAD

### ISSUE THREAD

**Issue by liessdow** [EoinAviation/VATPAC-ATIS-Generator-V2#2]
Even though it's an option in the ALI document for YPAD, the generator didn't include the RWY23/23 ARR RWY23 DEP option. So I added it! 
`
{
"name": "23&12 Arrivals, 23 Departures",
"text": "[RWY] 23 [AND] [RWY] 12 [FOR ARRS] , [RWY] 23 [FOR DEPS]",
"dir1": ["23", 222],
"dir2": ["12", 115]
},
`
If I could push this into the master, let me know :)

**Comment by YuKitsune** [comment]
Push all you like :)
